server:
  port: 8080

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
      enabled: false

drive-wealth:
  baseUrl: https://bo-api.drivewealth.io
  portfolioBenchMarkList:
    - name: S&P 500 Vanguard ETF
      uuid: 639247b6-cbcd-4616-841d-890dbb926575
  auth:
    scheduler:
      fixedRate: "18000000"
      initialDelay: "30000"
    retry:
      maxAttempts: 100
      maxDelay: 10
  dwClientAppKey: <>
  clientID: <>
  clientSecret: <>
