server:
  port: 8080

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
  cache:
    infinispan:
      config: infinispan-config.xml

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
      enabled: false
yahoo:
  finance:
    baseUrl: https://query1.finance.yahoo.com/
    scheduling:
      cron: "* */30 * * * ?"
    feeds:
    - id: latest
      name: Latest News
    - id: world
      name: World News